name: Arcana
description: Arcana template for Jekyll
paginate: 10
#baseurl: '/Arcana-Jekyll-Theme'

#My Stuff
gems: ['jekyll-paginate']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

